apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-to-mysql
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: app
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: data
      podSelector:
        matchLabels:
          app: mysql
    ports:
    - protocol: TCP
      port: 3306