apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policyattachments.iam.aws.namecheap.com
spec:
  group: iam.aws.namecheap.com
  names:
    kind: PolicyAttachment
    listKind: PolicyAttachmentList
    plural: policyattachments
    singular: policyattachment
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              policyName:
                type: string
              roleName:
                type: string
            required:
            - policyName
            - roleName 