apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mysql-secrets
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: ${secret_name}
      property: username
  - secretKey: password
    remoteRef:
      key: ${secret_name}
      property: password
  - secretKey: host
    remoteRef:
      key: ${secret_name}
      property: host
  - secretKey: port
    remoteRef:
      key: ${secret_name}
      property: port
  - secretKey: database
    remoteRef:
      key: ${secret_name}
      property: database