apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: slack-webhook-secret
    creationPolicy: Owner
  data:
  - secretKey: webhookUrl
    remoteRef:
      key: ${secret_name}
      property: webhookUrl