apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: weather-api-secrets
    creationPolicy: Owner
  data:
  - secretKey: weather-api-key
    remoteRef:
      key: ${secret_name}
      property: api_key