apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: ${name}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${region}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets 