apiVersion: v2
name: elasticsearch
description: A custom Helm chart for Elasticsearch using the official image
type: application
version: 0.1.0
appVersion: "8.10.4"
annotations:
  internal-only: "true"
  notes: "Elasticsearch deployed as internal-only service per project definition. No external ingress."