apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-secret-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["mysql-app-user-password-secret"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-secret-reader
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: mysql-secret-reader
  apiGroup: rbac.authorization.k8s.io 