dashboard:
  enable: true
  replicas: 1
  service:
    type: ClusterIP
  
webhook:
  enable: false
  mutate: false
  certManager:
    enabled: false # Disable cert-manager integration
  
  nodeSelector:
    node-role: management
  
  tolerations:
  - key: "management"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

audit:
  enable: false
  schedule: "0 */12 * * *"  # Twice daily
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  nodeSelector:
    node-role: management
  
  tolerations:
  - key: "management"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

config:
  checks:
    # Reliability checks
    readinessProbeMissing: danger
    livenessProbeMissing: warning
    
    # Security checks
    hostIPCSet: danger
    hostPIDSet: danger
    hostNetworkSet: warning
    privilegeEscalationAllowed: danger
    runAsRootAllowed: warning
    runAsPrivileged: danger
    notReadOnlyRootFilesystem: warning
    insecureCapabilities: danger
    
    # Resources checks
    cpuRequestsMissing: warning
    cpuLimitsMissing: warning
    memoryRequestsMissing: warning
    memoryLimitsMissing: warning